# invalid_inputs.py
invalid_inputs = {
    "aaa aaa", "bbb bbb", "ccc ccc", "zzz zzz", "aaa bbb", "sss sss", "sas sas", 
    "kaz kaz", "rus kaz", "kaz rus", "мен мен", "men men", "bot bot", "robot robot", "user user", 
    "qwerty qwerty", "asdf asdf", "test test", "abcd abcd", "qwert qwert",
    "aaaaa aaaaa", "admin admin", "password password", "root admin"
    "welcome welcome", "user user", "fake fake", "random random", 
    "dummy dummy", "guest guest", "root root", "test test", 
    "hello hello", "guest guest", "bog bog", "demon demon"
    "abc abc", "qwerty qwerty", "password password", 
    "username username", "testuser testuser", "qwerty qwerty", 
    "random random", "demo demo", "testaccount testaccount", 
    "demoaccount demoaccount", "faketest faketest", "userdemo userdemo", 
    "name name", "fakeuser fakeuser", "testaccount testaccount", 
    "adminaccount adminaccount", "guestaccount guestaccount", 
    "testemail testemail", "example example", "dummyuser dummyuser", 
    "testuser testuser", "fakeuser fakeuser", "admin root", "root admin"
    "qwertyadmin qwertyadmin", "adminadmin adminadmin", "rootadmin rootadmin", 
    "guestadmin guestadmin", "demoadmin demoadmin", "testpassword testpassword", 
    "testname testname", "adminname adminname", "demo demo",  "demoaccount demoaccount",  "fakeaccount fakeaccount", "guest guest", 
    "root root", "adminfake adminfake",
    "guesttest guesttest", "name name", "demo demo", 
    "password password", "testpassword testpassword", 
    "randompassword randompassword", "fakedata fakedata", "userfake userfake", 
    "testdata testdata", "rootname rootname", "demoaccountdemo demoaccountdemo", 
    "fakename fakename", "testaccountname testaccountname", "testname testname", 
    "adminplaceholder adminplaceholder", "guestplaceholder guestplaceholder", 
    "userplaceholder userplaceholder", "passwordtest passwordtest", 
    "invalidname invalidname", "emptydata emptydata", "dummynumber dummynumber", 
    "testnumber testnumber", "test test", "fakepassword fakepassword", 
    "invalidpassword invalidpassword", "datatest datatest", "qwertydata qwertydata", 
    "testuserdata testuserdata", "accountaccount accountaccount", 
    "usernameuser usernameuser", "adminadminadmin adminadminadmin", 
    "guestguest guestguest", "fakefake fakefake", "datadummy datadummy", 
    "qwerty qwerty", "adminplace adminplace", "userplace userplace", "пользователь пользователь", "имя имя", 
    "гость гость", "псевдоним псевдоним", "тест тест", "пароль пароль", 
    "фальшивка фальшивка", "рандом рандом", "заглушка заглушка", "тестировщик тестировщик", 
    "дема дема", "работник работник", "пользователь пользователь", 
    "гость гость", "имя имя", "фейк фейк", "ошибка ошибка", 
    "пробный пробный", "администратор администратор", "робот робот", "пустой пустой", 
    "неверный неверный", "псевдо псевдо", "система система", "запрещено запрещено", 
    "блокировка блокировка", "опыт опыт", "эксперт эксперт", "файл файл", "данные данные", 
    "глупый глупый", "тестовое тестовое", "пример пример", "блок блок", "неудача неудача", 
    "проверка проверка", "ошибочный ошибочный", "пароль пароль", "гостевой гостевой", 
    "служба служба", "ответ ответ", "запрещен запрещен", "невозможно невозможно", 
    "отказ отказ", "вход вход", "профиль профиль", "доступ доступ", "регистрация регистрация", 
    "система система", "база база", "сервер сервер", "работает работает", "попробуй попробуй", 
    "запрос запрос", "письмо письмо", "сохранение сохранение", "настройки настройки", 
    "пользователи пользователи", "профили профили", "рабочий рабочий", "партнер партнер", 
    "пользовательский пользовательский", "сохранить сохранить", "режим режим", "старт старт", 
    "обновить обновить", "кнопка кнопка", "доступность доступность", "установить установить", 
    "обработка обработка", "вывод вывод", "данные данные", "проект проект", 
    "поиск поиск", "система система", "подключение подключение", "включить включить", 
    "отключить отключить", "интерфейс интерфейс", "пользовательский интерфейс пользовательский интерфейс", 
    "работать работать", "управление управление", "проверка данных проверка данных", 
    "информация информация", "экран экран", "программа программа", "работа работа", 
    "сайт сайт", "сервис сервис", "разрешение разрешение", "условие условие", 
    "информация информация", "помощь помощь", "учет учет", "профессия профессия", 
    "кнопка кнопка", "расширение расширение", "функция функция", "парольпользователь парольпользователь", 
    "система система", "интерфейс интерфейс", "работающая работающая"
}
